In [1]:
import numpy as np


In [2]:
lista = [1, 2, 3, 4, 5, 6]
arrary = np.array(lista)
print(arrary)
print(lista)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [3]:
array_zeros = np.zeros(10)

In [4]:
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
lista_notas = [3.5, 9.9, 10.0, 7.8, 8.9]
array_notas = np.array(lista_notas)
print(array_notas)

[ 3.5  9.9 10.   7.8  8.9]


In [10]:
print('máximo', array_notas.max())
print('mínimo', array_notas.min())
print('mean', array_notas.mean())
print('std', array_notas.std())
print('model', array_notas.mode())

máximo 10.0
mínimo 3.5
mean 8.02
std 2.3961636004246456


AttributeError: 'numpy.ndarray' object has no attribute 'mode'